apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-istio
  namespace: {{ .Values.prometheus.serviceMonitorNamespace }}
  labels:
{{ toYaml .Values.prometheus.serviceMonitorLabels | indent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app: demo-app
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
