name: Build and Push Image

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "Dockerfile"
      - "requirements.txt"
      - "requirements-lock.txt"
      - ".github/workflows/build.yaml"

env:
  IMAGE: minglai/argo-canary-demo-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate version
        id: version
        run: |
          echo "VERSION=v${{ github.run_number }}" >> $GITHUB_OUTPUT
          echo "SEMANTIC_VERSION=${{ github.run_number }}.0.0" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: minglai
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ steps.version.outputs.VERSION }}
            ${{ env.IMAGE }}:latest

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: miku-wwl/argo-canary
          token: ${{ secrets.GH_PAT }}
          path: gitops

      - name: Update Helm values
        run: |
          cd gitops/infra/helm/demo-app
          sed -i "s/tag:.*/tag: ${{ steps.version.outputs.VERSION }}/" values.yaml

      - name: Update Helm Chart Version
        run: |
          cd gitops/infra/helm/demo-app
          sed -i "s/appVersion:.*/appVersion: ${{ steps.version.outputs.SEMANTIC_VERSION }}/" Chart.yaml

      - name: Commit and Push new Helm values
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "miku-wwl@users.noreply.github.com"
          git add infra/helm/demo-app/values.yaml infra/helm/demo-app/Chart.yaml
          if git diff --cached --quiet; then
            echo "No GitOps changes to commit"
          else
            git commit -m "Update image to ${{ steps.version.outputs.VERSION }}"
            git push origin HEAD:main
          fi
